### PR TITLE
Casacore 3.4 conversion

### PR DESCRIPTION
**Pull request by VoronkovMA**
I have made changes to casarest to bring it in line with casacore-3.4 (largely changes to includes, but also table row number type and block-based constructor of the vector). There is also some cleanup of compiler warnings. 

It seems practical to have a separate release of casarest once these changes are merged - the current most recent casarest-1.7.0 release is still required to build with older versions of casacore, but is not compatible with casacore-3.4.

### CODE REVIEW

**Comment by gijzelaerr** [comment]
thanks! How does this relate to the other PR https://github.com/casacore/casarest/pull/36 that we forgot to look at for too long?

**Comment by VoronkovMA** [comment]
It looked to me like both #36 and #35 cover for some aspects brought by casacore-3.4, but perhaps not all.

**Comment by VoronkovMA** [comment]
I can confirm that all changes of the first commit of PR #36 are among my changes too (i.e. explicit Regex instantiation based on String because DirectoryIterator constructor is now declared explicit as well as table row type change). However, I do not have changes matching the last two commits of PR #36 - it looks like André may have added this in response to comments on that PR to make the transition more backwards compatible. It is not clear to me how necessary this is (given that the transition to casacore-3.4 would require changes anyway in the users code, i.e. is not backwards compatible; also my version builds as is without this additional header), but it won't hurt. As common changes are textually identical, I wouldn't expect any conflicts between this PR and #36, they can be merged in any order.

**Comment by gijzelaerr** [comment]
there are merge conflicts with #36 and #35. I've reverted the merge and reopened a PR here https://github.com/casacore/casarest/pull/42

**Pull request merged**
