### PR TITLE
Removed use of old casacore Map, etc.

### PR DESCRIPTION
**Pull request by gervandiepen**
All old casacore classes (OrderedMap, List, Stack) have been replaced by their STL counterparts.
It requires now casarest to be built with casacore-3.1 or higher due to a small API change in casacore.

### CODE REVIEW

**Comment by bennahugo** [comment]
Apologies for not seeing this PR before I changed the dockerfiles before building. 
@Athanaseus can you please merge the conflict into the 3.1 build test and see if we can build casarest without the deprecated modules. We can then try and switch this to 3.2

**Comment by Athanaseus** [comment]
This PR when the conflicts are resolved builds fine with cc 311

**Comment by gijzelaerr** [comment]
can you issue a PR that resolve the conflicts and verify it works with casacore 3.2.1?

**Comment by Athanaseus** [comment]
https://github.com/casacore/casarest/pull/31

**Comment by Athanaseus** [comment]
cc-321 tests ongoing

**Comment by bennahugo** [comment]
Superseded by #31

**Pull request closed without merging**
