### PR TITLE
Build casarest against latest casacore (64bit + regex)

### PR DESCRIPTION
**Pull request by aroffringa**

### CODE REVIEW

**Comment by aroffringa** [comment]
This branch should be backward compatible. I've tested it with casacore 3.2 and that works.

**Comment by gijzelaerr** [comment]
i'm experiencing a compilation issue with casacore 3.4.0 on ubuntu 21.10:
```
gijs@gijs-artica:~/Work/astro/casarest/build (aroffringa-latest-casacore) 
λ  make  
[  0%] Building CXX object components/CMakeFiles/casa_components.dir/SpectralComponents/GaussianMultipletSpectralElement.cc.o
/home/gijs/Work/astro/casarest/components/SpectralComponents/GaussianMultipletSpectralElement.cc:29:10: fatal error: casacore/casa/Arrays/ArrayIO.h: No such file or directory
   29 | #include <casacore/casa/Arrays/ArrayIO.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [components/CMakeFiles/casa_components.dir/build.make:95: components/CMakeFiles/casa_components.dir/SpectralComponents/GaussianMultipletSpectralElement.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1051: components/CMakeFiles/casa_components.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
```

**Comment by gijzelaerr** [comment]
https://github.com/casacore/casarest/pull/42 compiles without issues on 3.4.0, what do you think?

**Comment by aroffringa** [comment]
They should be merged both; this one probably first.

**Pull request merged**
